import type { IconType } from "react-icons";
import {
  SiApachekafka,
  SiApachemaven,
  SiBruno,
  SiC,
  SiDocker,
  SiGit,
  SiGithubactions,
  SiGrafana,
  SiHibernate,
  SiJaeger,
  SiJavascript,
  SiJunit5,
  SiKubernetes,
  SiLinux,
  SiLiquibase,
  SiMinio,
  SiNginx,
  SiOpenapiinitiative,
  SiOpenjdk,
  SiOpentelemetry,
  SiPostgresql,
  SiPrometheus,
  SiPytest,
  SiPython,
  SiRailway,
  SiReact,
  SiRedis,
  SiSentry,
  SiSocketdotio,
  SiSpringboot,
  SiSpringsecurity,
  SiSupabase,
  SiTypescript,
} from "react-icons/si";
import {
  FaAws,
  FaCode,
  FaCube,
  FaDatabase,
  FaEye,
  FaFlask,
  FaLayerGroup,
  FaMasksTheater,
  FaNetworkWired,
  FaRobot,
} from "react-icons/fa6";

const icons: Record<string, IconType> = {
  Java: SiOpenjdk,
  Python: SiPython,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  SQL: FaDatabase,
  C: SiC,
  "Spring Boot": SiSpringboot,
  "Spring Security (OAuth2/JWT)": SiSpringsecurity,
  "Spring Batch": FaLayerGroup,
  "Apache Kafka": SiApachekafka,
  "Hibernate/JPA": SiHibernate,
  "REST APIs": FaNetworkWired,
  "WebSocket/STOMP": SiSocketdotio,
  React: SiReact,
  JUnit: SiJunit5,
  Mockito: FaFlask,
  Testcontainers: FaCube,
  pytest: SiPytest,
  Playwright: FaMasksTheater,
  Kubernetes: SiKubernetes,
  Docker: SiDocker,
  AWS: FaAws,
  Railway: SiRailway,
  Linux: SiLinux,
  Nginx: SiNginx,
  PostgreSQL: SiPostgresql,
  Redis: SiRedis,
  Supabase: SiSupabase,
  MinIO: SiMinio,
  Liquibase: SiLiquibase,
  Git: SiGit,
  "GitHub Actions (CI/CD)": SiGithubactions,
  Prometheus: SiPrometheus,
  Grafana: SiGrafana,
  Micrometer: FaEye,
  Sentry: SiSentry,
  OpenTelemetry: SiOpentelemetry,
  Jaeger: SiJaeger,
  Bruno: SiBruno,
  Maven: SiApachemaven,
  "OpenAPI/Swagger": SiOpenapiinitiative,
  "OpenAI API": FaRobot,
};

export default function TechIcon({ name }: { name: string }) {
  const Icon = icons[name] ?? FaCode;

  return <Icon aria-hidden="true" focusable="false" />;
}
